### ISSUE TITLE
hassio.addon_stdin deprecation, example may need updating

### ISSUE THREAD

**Issue by johntdyer** [matthewhadley/homeassistant-dropback#12]
Hello,  

 It appears that [hassio.addon_stdin](https://community.home-assistant.io/t/replacement-for-this-service-hassio-addon-stdin/399824) is deprecated..  what should we replace it with ?  Figured you might also want to update the example

Thanks !

**Comment by matthewhadley** [comment]
Thanks @johntdyer, I will investigate

**Comment by matthewhadley** [comment]
@johntdyer from what I read (and note that thread is from March '22), the service is not deprecated (I also see no deprecation warnings in HA logs when using it), but its use was removed in the ssh add-on _only_, see: https://github.com/hassio-addons/repository/blob/9d08973517f1e7cb2808e79a8518cefad859a463/ssh/CHANGELOG.md

As such, will close this issue.

**Comment by johntdyer** [comment]
thank you for the clarification !!!
