### ISSUE TITLE
Usage with network storage

### ISSUE THREAD

**Issue by jiiins** [matthewhadley/homeassistant-dropback#13]
Hello,

I currently save the backups to a USB drive, mapped using HA's network storage facility. Since it's in the same physical location as the HA server, I'd prefer to upload to Dropbox just in case. I thought of mapping the the USB drive to the `/backup' folder, but I'm not sure if it survives reboots and updates, since it's a special folder. Otherwise, I could backup locally and then do a cron job to copy to the USB drive, but then I don't have control over the number of backups retained...

Could you maybe suggest an efficient way?

Cheers

**Comment by matthewhadley** [comment]
This is outside of the scope of Dropback, but I think your suggestion is the way I'd go; an automation that does:
- a local backup
- makes a copy of that backup to the USB drive
- syncs the local backup(s) to dropbox (and old local backups can get deleted)
You could maybe have the automation include some logic to check how many backups are on the USB drive - this might have to be in a script the automation calls
