### ISSUE TITLE
Trying first backup - failed

### ISSUE THREAD

**Issue by IanAdd** [matthewhadley/homeassistant-dropback#3]
Hi I get an error at the end of the startup.
\\\
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2022-09-10 16:47:57] INFO: Initializing Dropback
[2022-09-10 16:47:57] INFO: No config file found, requesting long lived Refresh Token...
[2022-09-10 16:47:58] INFO: Got Refresh Token
[2022-09-10 16:47:58] INFO: Config file saved
[2022-09-10 16:47:58] INFO: Validating Dropbox access... 
[2022-09-10 16:48:00] INFO: Dropbox access OK
[2022-09-10 16:48:00] INFO: Listening for input via stdin service call...
[2022-09-10 16:48:16] INFO: Received input: sync
[2022-09-10 16:48:16] INFO: Syncing local files to Dropbox...
curl: (6) Could not resolve host: content.dropboxapi.com
\\\
Any ideas ?

**Comment by IanAdd** [comment]
Actually, after a while it completed a backup so it is just an information message of no meaning to a user, I assume.

**Comment by matthewhadley** [comment]
Hi @IanAdd, thanks for the report and including the log output.

`curl: (6) Could not resolve host: content.dropboxapi.com`

It looks like there was an issue resolving the host `content.dropboxapi.com`

`curl` is the program that handles the actual uploading of the backups and it was unable to find dropbox for some reason - there might have been a network issue that was making dropbox unreachable.

Was there any more log output or did it stop there?

**Comment by matthewhadley** [comment]
I've released version `5.0.0` which includes a check for network connectivity to Dropbox

**Comment by IanAdd** [comment]
> 

@matthewhadley It just went on the do the backups, no more error messages.

**Comment by matthewhadley** [comment]
Thanks @IanAdd. I'm going to close this issue, but please reach out if there are any problems.
