### ISSUE TITLE
Files with "/" in name get put into directories

### ISSUE THREAD

**Issue by rsnodgrass** [matthewhadley/homeassistant-dropback#6]
Any backup file that has a slash in its name (such as a date like 2022/12/3) get uploaded into subdirectories based on the slashes, rather than just as part of the filename.

**Comment by matthewhadley** [comment]
This is default filesystem behavior for slashes in the final path name. The only way to change this would be for dropback to replace any `/` with another character (which would prevent creating subdirectories from the backup name if that was desired). That could also be done in the process that's creating the backup file (before dropback is involved), which is what I would recommend.

**Comment by matthewhadley** [comment]
Closing this as this should be handled in the backup name.

**Comment by rsnodgrass** [comment]
@matthewhadley, shouldn't Dropback be escaping any existence of "/" characters when generating filename from the backup name?

E.g. in get_dropbox_file_path() escaping the / from the backup name (using sed for instance):

```
BACKUP_NAME=$(bashio::api.supervisor "GET" "$BACKUP_API/$SLUG/info" | jq -r .name | sed 's/\//\\\//g') 
```


For example, the snapshot filename is 'Auto Backup: Fri, 9:00 PM (02/12/2022)'. Using slashes in the backup name is default behavior for autoback.

**Comment by matthewhadley** [comment]
Having a slash in the final name - even if "escaped" - won't be supported by any filesystem as filenames can't have slashes in them at all.

Possibly there could be an extra option in dropback to support "replace slashes in backup names with custom character [x]" (where x is user defined).

> Using slashes in the backup name is default behavior for autoback.

I'm not familiar with autoback, but if I am looking at the right page it looks like you can specify a backup name format (without slashes): https://jcwillox.github.io/hass-auto-backup/services/#auto_backupbackup_full

**Comment by rsnodgrass** [comment]
I shouldn't be posting when recovering from the flu! Of course, you are correct no slashes in filenames.

You can ignore this request.

**Comment by matthewhadley** [comment]
@rsnodgrass no problem! Hope you're fully recovered
