### ISSUE TITLE
sensors - enhancement ?

### ISSUE THREAD

**Issue by IanAdd** [matthewhadley/homeassistant-dropback#7]
I had naively imagined the sensor.dropback_running would give me a means of knowing when it was 'working', ie moving files(s).

From such a sensor I could know how long a backup move was taking; have easy confirmation that it had completed, etc.

Is there any chance of such a sensor ?

**Comment by matthewhadley** [comment]
In version `7.0.0`, released yesterday, some of the sensors were renamed. The `sensor.dropback_sync` sensor (renamed from `dropback.sync`) should give you the information you are after - it shows the current file being processed. When added to the logbook card, mine looks like this:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/36013/210482968-5a7579e9-27b0-4475-a236-e08d7c12825e.png">

Note that Dropback syncs all the files - so older backups are checked to exist in Dropbox and will have very short "sync" times vs new backups that are being uploaded as part of the sync.

**Comment by IanAdd** [comment]
Thanks, I can work with that, I think.

**Comment by IanAdd** [comment]
Actually, I remain confused.

I triggered dropback service and now the sensor.dropback_sync is still showing the last file it uploaded on my system, however your log suggests that it should revert to 'None'.

I also have found another sensor.dropback_last which shows the name of the previous system backup, not the last item it backed up which was your add-on being backed up as a result of me upgrading to your version 7.0.0

Other mysteries are:
1) the 'device' dropback lists a number of hidden and visible sensors but neither of these two sensors are listed.
2) the HA log has started reporting 'Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}''
Is this by any chance from your add-on ? It isn't in any of my yaml scripts.

**Comment by jamesmyatt** [comment]
I don't see these sensors on my install. Am I looking in the wrong place or is there something I need to do to enable them, like installing an integration?

**Comment by IanAdd** [comment]
James, I am assuming you have the dropback add-on installed.
The weird thing I reported above is that the sync and last sensors show up in the entities list (look under 'settings' then 'devices and services' then the 'entities' tab but not in the list of entities for the dropback 'device' in the 'devices' tab.

**Comment by jamesmyatt** [comment]
They've appeared after I ran the sync again. As you say, they're not associated with any "device".

**Comment by matthewhadley** [comment]
Sorry you're having trouble @IanAdd 

> I triggered dropback service and now the sensor.dropback_sync is still showing the last file it uploaded on my system, however your log suggests that it should revert to 'None'.

It should only show the current file being processed, so when it has finished it should revert to 'None'. Perhaps there was an unexpected error. Do you see anything in the logs for the add-on? (select the "Log" tab on the Dropback Add-on page).

> I also have found another sensor.dropback_last which shows the name of the previous system backup, not the last item it backed up which was your add-on being backed up as a result of me upgrading to your version 7.0.0

Renaming the sensors (which happened in version 7.0.0) will have broken any history unfortunately. Assuming a successful backup run (though it seems there may have been an error in your case and we should check the logs) the `sensor.dropback_last` should then have the last file to have successfully sync'd.

> Other mysteries are:
> 
> 1. the 'device' dropback lists a number of hidden and visible sensors but neither of these two sensors are listed.

The sensors on the device page for Dropback are generated by Home Assistant and are generic ones that Home Assistant creates for all Add-Ons. 

I'm not aware of a way for me to associate sensors that the Dropback Add-On itself creates to the Dropback "device" - I would like to, maybe I am missing something in the developer docs.

> 2. the HA log has started reporting 'Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}''
>    Is this by any chance from your add-on ? It isn't in any of my yaml scripts.

I don't believe this warning is coming from Dropback. I found mention of a similar error on the [Home Assistant Forums](https://community.home-assistant.io/t/help-debugging-homeassistant-helpers-template/512450)

---

@jamesmyatt as of version `7.0.0` Dropback should create 3 sensors:
```
  - entity: sensor.dropback_status
  - entity: sensor.dropback_sync
  - entity: sensor.dropback_last
```

- `sensor.dropback_status` with the current status of the add-on:
  - OK (on start-up and updated on each succesful file sync to Dropbox)
  - Error (an error occured preventing sync to Dropbox)
- `sensor.dropback_sync` showing the file currently being sync'd.
- `sensor.dropback_last` showing the last file sync'd.

They should become available when Dropback does its first sync execution. Unfortunately they do not persist through Home Assistant restarts - similar to Home Assistant Template sensors.
