### ISSUE TITLE
offline but online

### ISSUE THREAD

**Issue by Doctorgspot** [matthewhadley/homeassistant-dropback#8]
Hi,

So I'm new to home assistant I've probably spent about 48hrs messing around with it so far. I found your backup software and had a few issues setting it up. But the addon seems to now be running. everything is green in the log. but for some reason the 2 icons that shows its active are greyed out and red. Basically i installed it couldn't get it working. re-did all the steps from scratch then got it going. With the above caveat. 

Ive not got the automatic backup working yet as i say new to home assistant. But i thought id drop this too you as im not sure if you had seen this issue before.

**Comment by matthewhadley** [comment]
Hi @Doctorgspot, sorry to hear you had some issues and I hope you are enjoying home assistant. If the logs tab isn't showing errors and you're able to initiate a backup manually (see https://github.com/matthewhadley/homeassistant-dropback/blob/master/dropback/DOCS.md#usage) then things should be ok. I have sometimes seen home assistant show add-ons as being inactive when I know they're running ok. If the inactive state persists you can try restarting home assistant.

**Comment by Doctorgspot** [comment]
Hi mate,
yeah i checked today and the backup ran fine. So im guessing its an home assistant issue. Ive restarted a fair few times and its still doing the same. But as long as its working its fine by me lol. Im a techie so i did try as many things as i could before hand. But like i say new to home assistant so bit of a up hill climb right now. 
Thanks for getting back in touch with me and good work.
kind regards,
Glenn
    On Tuesday, April 18, 2023 at 05:05:52 AM GMT+1, Matthew Hadley ***@***.***> wrote:  
 
 


Hi @Doctorgspot, sorry to hear you had some issues and I hope you are enjoying home assistant. If the logs tab isn't showing errors and you're able to initiate a backup manually (see https://github.com/matthewhadley/homeassistant-dropback/blob/master/dropback/DOCS.md#usage) then things should be ok. I have sometimes seen home assistant show add-ons as being inactive when I know they're running ok. If the inactive state persists you can try restarting home assistant.

**Comment by matthewhadley** [comment]
I'd like to help dig into it a bit more. 

- Can you add a screenshot of what you're seeing?
- Can you have a look in the home assistant full logs and see any output related to "add-ons"?
- What version of home assistant are you currently on? (I'm currently on `core-2023.3.6`, which is one major release behind)

**Comment by matthewhadley** [comment]
Closing out as things sound to be working

**Comment by Doctorgspot** [comment]
Hi mate,  im so sorry.  I havent bothered to even look at home assistant for a good 6 weeks.  So no idea what its up too.  Good weather has kept me outside lol ill have to see what its been up to etc and let you know asap. 
Kind regards, 
Glenn

Sent from Yahoo Mail on Android 
 
  On Fri, 2 Jun 2023 at 16:58, Matthew ***@***.***> wrote:   


Closed #8 as completed.
